- type: entity
  id: LockerServiceAdministratorFilled
  suffix: Filled
  parent: LockerServiceAdministrator
  components:
  - type: StorageFill
    contents:
    - id: DrinkGlass
      amount: 5
    - id: DrinkShotGlass
      amount: 5
    - id: DrinkShaker
      amount: 2
    - id: DrinkOrangeJuice
      amount: 2
    - id: DrinkLimeJuice
      amount: 2
    - id: DrinkTomatoJuice
      amount: 2
    - id: DrinkWaterBottleFull
      amount: 2
    - id: DrinkSodaWaterCan
      amount: 2
    - id: DrinkCreamCarton
      amount: 2

- type: entity
  id: LockerChefCookFilled
  suffix: Filled
  parent: LockerChefCook
  components:
  - type: StorageFill
    contents:
    - id: ReagentContainerFlour
      amount: 3
    - id: ReagentContainerRice
      amount: 3
    - id: DrinkMilkCarton
      amount: 4
    - id: DrinkSoyMilkCarton
      amount: 2
    - id: ReagentContainerSugar
      amount: 2
    - id: FoodCondimentPacketSalt
      amount: 3
    - id: FoodCondimentBottleEnzyme
      amount: 2
    - id: FoodContainerEgg
      amount: 2
    - id: KitchenKnife
