- type: gameMapPool
  id: FtCMapPool #FtC-Edit
  maps:
  - BagelFtC
  - BoxFtC
  - CogFtC
  - CoreFtC
  - FlandFtC
  - MarathonFtC
  - MetaFtC
  - OasisFtC
  - OmegaFtC
  - PackedFtC
  - ReachFtC
  - TrainFtC

- type: weightedRandom
  id: DefaultCentcomPool
  weights:
    CentComm: 0.5
